### ISSUE TITLE
Issues Counter Wrong?

### ISSUE THREAD

**Issue by Xelloss-nakama** [cbanack/comic-vine-scraper#426]
Is there any reason why the issues counter always show -1 value respect real number in the Series List?

I understand that in programming 0 is the first position, but... It is just weird to see things like "0 issues" XD

**Comment by cbanack** [comment]
This is a [long-standing problem](https://github.com/cbanack/comic-vine-scraper/issues/46) with the Comic Vine database.  For some reason, it takes a few days for the database to start reporting the correct issue count back to the scraper when a new issue has been added.

If a new issue has been added very recently (like in the last couple of days), the database always reports a number that is 1 too low.  Then after a while, it gets itself straightened out and the right number of issues are reported.   The right number of issues is always reported for older series that have not had issues added to them recently.

Anyway, there's not much that can be done to fix the problem in the scraper code--this is something for Comic Vine to fix in their public API.   And since they've known about the problem for years, I wouldn't hold your breath... :/
