### ISSUE TITLE
Scraper not pulling Rating

### ISSUE THREAD

**Issue by Matchiz** [cbanack/comic-vine-scraper#434]
Was curious, looked over the API, this and Comic rack Forums and no one is mentioning this directly, I have the latest Comic Rack Scraper and it will not pull ratings. Currently I have in the advanced settings;

Community_scrape_Rating=true
user_review_average=True

But nothing is pulled. Is this ability no longer accessible?

**Comment by cbanack** [comment]
I'm not sure where you got those settings from; I don't recognize them.  The list of supported advanced settings is here: https://github.com/cbanack/comic-vine-scraper/wiki/Advanced-Settings

There used to be a setting called "scrape_rating", but it is no longer available due to complaints from Comicvine.  See here: https://github.com/cbanack/comic-vine-scraper/issues/421
