### ISSUE TITLE
Scraper not Fetching any thumbnails

### ISSUE THREAD

**Issue by riancopper** [cbanack/comic-vine-scraper#438]
Whenever I started the scraper before this it would let me browse the image files of the series. Now when I try to use it, it won't show me anything. When I try to scrape fileless entries the scraper also fails to add them to the files. I have tried uninstalling and reinstalling, and I am using up to date versions of comicrack and all my addons. Any help would be much appreciated!

**Comment by cbanack** [comment]
This issue will be fixed, but not for a few weeks.   There is discussion on the ComicRack forums about what's going on and why.  Also, there is a temporary work around described there that you can do if you are comfortable making minor edits to your Comic Vine Scraper code.

See:

http://comicrack.cyolito.com/forum/32-news-and-announcements/33534-comic-vine-scraper?start=1130#45812

**Comment by cbanack** [comment]
This, specifically, is the work around:. 

http://comicrack.cyolito.com/forum/32-news-and-announcements/33534-comic-vine-scraper?start=1140#45821

**Comment by Clearmist** [comment]
I modified the files the way Scuttle wrote, rebuilt the plugin in to a .crplugin file, reinstalled the plugin and the covers are still not being obtained. Perhaps there exists a cached version of the plugin that is simply re-enabled instead of being overwritten when reinstalling? Well, I tried that by incrementing the version number and the same problem still exists.

**Comment by cbanack** [comment]
Fixed in 1.0.93.
