### ISSUE TITLE
Scrapper not working  for queries with a big payload result

### ISSUE THREAD

**Issue by andrelopesmrx** [cbanack/comic-vine-scraper#449]
How to reproduce:
Scrap by: "Superman"  or
Scrap by: "Robin" 

I believe it may or may not be related to the default limit reduced to 10:
https://comicvine.gamespot.com/forums/api-developers-2334/changing-search-apis-default-limit-down-to-10-1830541/#2

**Comment by cbanack** [comment]
I think it is a bug on ComicVine's server.  We are discussing the issue here:

http://comicrack.cyolito.com/forum/32-news-and-announcements/33534-comic-vine-scraper?start=1340#48551

Note that I have raised bug report in the Comic Vine forum, here:

https://comicvine.gamespot.com/forums/bug-reporting-2/api-request-times-out-for-certain-queries-1908981/

**Comment by cbanack** [comment]
There is [some evidence](https://comicvine.gamespot.com/forums/bug-reporting-2/api-request-times-out-for-certain-queries-1908981/?page=1#js-message-19478119) that the Comic Vine engineers are working on this problem.

**Comment by jtucker** [comment]
Appears to be [fixed](https://comicvine.gamespot.com/forums/bug-reporting-2/api-request-times-out-for-certain-queries-1908981/?page=1#js-message-19501382). I just tried it and finally got all my `Superman` comics tagged.
