### ISSUE TITLE
Comic Vine API returns too many results

### ISSUE THREAD

**Issue by metalracket** [cbanack/comic-vine-scraper#460]
As of today when I'm scrapping my comics it is giving me a list of all series that contains any word from the title of comic

Example:

Scraped "Deadman: Dark Mansion of Forbidden Love" got back 1689 matches including a series titled "Love"
 
Updated from 1.0.92 to 1.0.96 but no change
![scrap it all](https://user-images.githubusercontent.com/45623613/49504282-7170c480-f8cd-11e8-92b2-93bcc420eb5e.jpg)

**Comment by Targg** [comment]
I am having the same issue, and posted on the CR forum, but since it is overrun by bots I am not sure if anyone will see it there.

As of yesterday afternoon, I am seeing some odd behaviors with the scraper. I had been scraping about 1000 comics a day this week, and yesterday the behavior changed.

It seems to now be giving results based on any of the words in the title. For example "X-Men vs Fantastic Four" would show results for "X-Men" "Fantastic" "Four" and "vs". The results list takes literally minutes to populate (it took seconds a few days ago), and the number of results shows in the thousands.

Nothing on my end has changed. I hadn't even closed ComicRack when the behavior changed.

Is there a way to limit the amount of search results? Anything with a common word or comic term (such as Spider-Man) takes forever, even when the specific title is very unique.

Thanks in advance for any help!

**Comment by boshuda** [comment]
I haven't investigated this at all, and haven't used the scraper in several days.  However, if the behaviour has actually changed then it's likely that ComicVine changed their search function again.  They have done it before without notifying the people who use their API.  Give it some time and/or check their forums.  In the meantime the workaround that I've found most effective is to pick the word least likely to be in hundreds of matches and search on that. It's also helpful if you fill in as much of the data as reasonable first.  If you visit comicrack's forums there is a script hidden in there somewhere that can autofill the volume.  That alone can help a lot before scraping.  If you can put the ComicVine id in place, that is usually the most surefire method I know of to get past search issues.  Again, the comic rack forums (unless the spam has destroyed them) has some more information on that.

**Comment by Targg** [comment]
To give a specific example, a search for "Untold Tales of the New Universe: Psi-Force" comes back with 3,194 results, so it's giving results for each word.

**Comment by cbanack** [comment]
Hi guys, 

I'm sure it must be something like what boshuda says -- the API has changed.   They just seem to do that every now and then.

I'll look into it more when I get a chance (probably this weekend); hopefully it's a simple fix like it was last time they did this.

Cory

**Comment by cbanack** [comment]
Ok, I've looked into this a bit, and I can confirm that I'm seeing the same behaviour (search terms are being OR'd now, when they used to be AND'd).    It definitely slows things down, but it's nothing wrong with the scraper.   Comic Vine has silently changed how their search API works.    Unfortunately, I don't really have a solution to the problem -- the fix pretty much as to be on their end.

So I've posted a message in their forums explaining the matter:

https://comicvine.gamespot.com/forums/api-developers-2334/apis-search-resource-broken-1990887/

Also, I recall that we had this exact same problem about a year ago:

https://www.giantbomb.com/forums/bug-reporting-33/new-search-system-going-live-1817994/?page=2#js-message-8775319

Back then, ComicVine ultimately fixed the problem on their end.   In a lot of ways, this feels like they've recently lost that fix somehow.   But maybe they'll be willing to do it again.

**Comment by fieldhouse** [comment]
One thing that really helps as a workaround is Xelloss' Autocomplete Volume Values script.  
It helps speed up the guesswork/pre-processing by adding the comicvine_volume custom value to any recognized comics. The scraping for those recognized issues goes back to the previously experienced rate (probably a little faster since it's jumping straight to the one series).
http://comicrack.cyolito.com/forum/13-scripts/39594-auto-complete-volume-values-script-beta
Make sure you grab the most recent version - 1.8 last I checked - http://comicrack.cyolito.com/forum/13-scripts/39594-script-auto-complete-volume-values-script-beta?start=10#48108

**Comment by Xelloss-nakama** [comment]
It is not exactly a FULL fix, but you can try my old patch (which still works this time) to scrap comics while this is fixed...

http://comicrack.cyolito.com/forum/32-news-and-announcements/33534-comic-vine-scraper?start=1630

(you have to replace a file in the excelent comicrack scraper script for it to works)

What the fix does is stop asking for results when the results are "good enough". This works because the new API search engine sort the best results first (the most similar to your search). It is not a 100% solution, but it works most of the times...

**Comment by cbanack** [comment]
Hey guys,

I finally got a chance to do something about this issue.   (To be honest, I've been kinda hoping that Comic Vine would address the problem on their end, but since that doesn't seem like it's going to happen, I've patched a sort-of-decent solution into the official version of the scraper.)

The following is loosely based on what Xelloss did in his patch (mentioned above).

There is now a new advanced property called [MAX_SEARCH_RESULTS](https://github.com/cbanack/comic-vine-scraper/wiki/Advanced-Settings#max_search_results) which can be used to determine how many results the scraper pulls down from Comic Vine when you search for a comic series.   The default value is set to 100, which is a good value since that's how many results come down with a single request to the Comic Vine API.  (And it seems to work well enough for most scrapes.)

You can adjust this value in the advanced settings section of your scraper config, but most people will not need to do this.  Just install the latest version of the scraper, and things will more or less work properly again...except when they don't of course.  :)  

This change assumes that the series you are looking for is always in the first 100 results that ComicVine returns. which it usually is.   But if it is not, it will seem like the scraper cannot find your series.   You *could* fix this by increasing the MAX_SEARCH_RESULTS value, but that will make all your other searches slower.

A better solution is to simply paste the URL of the Comic Vine webpage for your series directly into the search dialog of the scraper.   This will automatically force the scraper to find that series.   For example, to find Detective Comics, just search for:

http://www.comicvine.gamespot.com/detective-comics/4050-18058/

or even just:

4050-18058

Another good option might be to sort your series into folders and create a cvinfo file, as described here:

https://github.com/cbanack/comic-vine-scraper/wiki/CVINFO-and-CVDB-tags
