### ISSUE TITLE
[Enhancement] - Add delay after each html web request

### ISSUE THREAD

**Issue by killo3967** [cbanack/comic-vine-scraper#497]
Due to changes in comicvine's policy, it is necessary to wait at least 1 second after each html request to their api. 
Not to be confused with the timeout between comics, this is after each html request.

In the terms of use:
https://comicvine.gamespot.com/api/

Here is some more clarification:
https://comicvine.gamespot.com/forums/api-developers-2334/api-rate-limiting-1746419/

Could you implement a DELAY_AFTER_APIREQUEST or something similar in the configuration and in the program to solve this problem?

**Comment by cbanack** [comment]
Hmmm...that's a little more reasonable than their old policy, though I still don't see why they don't implement the throttling on their own end like a normal web API.

Anyway, yes I will look into doing this.  It will take me at least a week or two if not more because of summer trips and other things that are keeping me busy right now. 

If someone wants to submit a pull request with the necessary code changes instead, I would also be fine to review and use that.

**Comment by cbanack** [comment]
Can you confirm that you are actually experiencing any problems as a result of the new ComicVine policy?

I took a quick look at the code this evening, I see that I implemented a 1.1 second API throttling many years ago, and I tested it and the ComicVineScraper definitely still uses it.    So it looks to me like the current version of ComicVineScraper should be working fine?

**Comment by cbanack** [comment]
Actually, now that I look closer, that post you linked to is 8 years old, so this is not a new ComicVine policy at all.   Which explains why I implemented that 1.1 second throttling long ago (so long ago that I forgot I even did it.)   So rest assured, the scraper does not violate the 1 second-per-api-call rule.  (And hasn't for a long time.)

The real problem is, ComicVine found that allowing unlimited API requests every 1 second was still not throttling things enough, so they also limited the maximum number of API requests per hour (or minute, or day ... no one is really sure, and sometimes it changes.)   If you go over the limit, your API key gets banned for a while.

This restriction kind of breaks their API I think, but they don't seem to care.   For ComicVineScraper users, the workaround is to use the SCRAPE_DELAY advanced setting to limit the number of comics scraped per minute/day/hour.    I can't remember off the top of my head what the correct number to use for the scrape delay is, but it's something high (like 20 or 30 seconds or something) that makes scraping incredibly slow.    But this is the only way to scrape large numbers of comics all at once.

If you search (or ask) people over at https://www.reddit.com/r/comicrackusers/, I'm sure they will be able to tell you which SCRAPE_DELAY value currently works best.

**Comment by killo3967** [comment]
Sorry for take too long to respond toy you. I made a lot of test and, as you said, the only option i find is to
assign SCRAPE_DELAY to 35 second's. Anyway thanks a lot for your interest.
